name: Sign in

on:
  # push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  sign-in:
    runs-on: bun-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sign in
        env:
          BBS_USERNAME: ${{ secrets.BBS_USERNAME || vars.BBS_USERNAME }}
          BBS_PASSWORD: ${{ secrets.BBS_PASSWORD || vars.BBS_PASSWORD }}
          AUTO_EXCHANGE: ${{ secrets.AUTO_EXCHANGE || vars.AUTO_EXCHANGE }}
          FAILED_WEBHOOK: ${{ secrets.FAILED_WEBHOOK || vars.FAILED_WEBHOOK }}
        run: bun .
