name: Sign in

on:
  # push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  sign-in:
    runs-on: bun-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sign in
        env:
          BBS_AUTH: ${{ secrets.BBS_AUTH }}
          AUTO_EXCHANGE: ${{ secrets.AUTO_EXCHANGE }}
        run: bun .
